using UnityEngine;
using UnityEngine.AI;

namespace UnityTechnologies._3DBeginnerTutorial.Scripts {
	public class WaypointPatrol : MonoBehaviour
	{
		public NavMeshAgent navMeshAgent;
		public Transform[] waypoints;

		private int m_CurrentWaypointIndex;

		private void Start () {
			navMeshAgent.SetDestination (waypoints[0].position);
		}

		private void Update () {
			if(navMeshAgent.remainingDistance < navMeshAgent.stoppingDistance) {
				m_CurrentWaypointIndex = (m_CurrentWaypointIndex + 1) % waypoints.Length;
				navMeshAgent.SetDestination (waypoints[m_CurrentWaypointIndex].position);
			}
		}
	}
}